### PR TITLE
Replace features with cfg and autodetection

### PR DESCRIPTION
**Pull request by gkoz**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Thanks ! I wait for checks before merging.

**Comment by gkoz** [comment]
Yeah there's an ICE, I'll need to update the Rust version in appveyor first.

**Comment by GuillaumeGomez** [comment]
I have an ICE on gtk. It must be the bad week. I'll wait for your update then. ^^

**Comment by GuillaumeGomez** [comment]
And the problem is also on travis. Congrats ! haha

**Comment by gkoz** [comment]
Apparently `rustc` doesn't like bare `--cfg` and cargo doesn't bother to check.

**Comment by GuillaumeGomez** [comment]
You're using a deprecated item in `build.rs`.

**Comment by gkoz** [comment]
`join` hasn't made it into stable yet so...

**Comment by GuillaumeGomez** [comment]
erf... So annoying. Let's merge it for now. Thanks a lot for your work !

**Pull request merged**
